version: '2'

services:
  redis:
    restart: "always"
    image: redis:alpine
    volumes:
      - ./data/redis:/data

  nginx:
    restart: "always"
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  postgis:
    restart: "always"
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    env_file:
      - ./common.env
    environment:
      PGDATA: /var/lib/postgresql/data/PGDATA
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
      #- ./data/riverflows-dump/roles.sql:/docker-entrypoint-initdb.d/roles.sql
      #- ./data/riverflows-dump/dump.sql:/docker-entrypoint-initdb.d/zdump.sql
      #- ./postgis/initdb-pghoard.sh:/docker-entrypoint-initdb.d/pghoard.sh

  web:
    restart: "always"
    build: ./web
    expose:
      - "8000"
    links:
      - postgis:postgis
      - redis:redis
    command: "gunicorn --log-level debug --log-config logging.conf -w 2 -b :8000 wsgi:app"
    volumes:
      - .:/app
    env_file:
      - ./common.env

  celery:
    restart: "always"
    build: "./web"
    links:
      - postgis:postgis
      - redis:redis
    volumes:
      - .:/app
    env_file:
      - ./common.env
    environment:
      - NUM_WORKERS=5
    command: "celery worker -A celery_worker.celery -l info"

  celery-beat:
    restart: "always"
    build: "./web"
    links:
      - postgis:postgis
      - redis:redis
    volumes:
      - .:/app
    env_file:
      - ./common.env
    command: "celery beat -A celery_worker.celery -l info"
