version: '2'

services: 
    postgis:
        image: "mdillon/postgis:9.6"
        environment:
        - POSTGRES_PASSWORD=testing
        - POSTGRES_DB=gage-web
    
    web:
        build: ./web
        links:
        - postgis:postgis
        command: "python /app/manage.py runserver -d -r -p 8000 --host=0.0.0.0"
        volumes:
        - ./web:/usr/src/app
        environment: 
        - GAGE_DB=postgresql://postgres:testing@postgis/gage-web
    
    wait:
        links:
        - postgis:postgis
        image: waisbrot/wait
        environment:
        - TARGETS=postgis:5432