version: '2'

services: 
    postgis:
        image: "mdillon/postgis:9.6@sha256:4512d076541461f1e5d3178dcd37fedaf59af66e679310c412677222f629ed49"
        environment:
        - POSTGRES_PASSWORD=testing
        - POSTGRES_DB=gage-web
    
    web:
        build: ./web
        links:
        - postgis:postgis
        command: "python /usr/src/app/manage.py runserver -d -r -p 8000 --host=0.0.0.0"
        volumes:
        - ./web:/usr/src/app
        environment: 
        - GAGE_DB=postgresql://postgres:testing@postgis/gage-web
    
    wait:
        links:
        - postgis:postgis
        image: waisbrot/wait@sha256:6f2185daa4ab1711181c30d03f565508e8e978ebd0f263030e7de98deee5f330
        environment:
        - TARGETS=postgis:5432