apiVersion: v1
kind: Service
metadata:
  name: etcd-patroni-cluster
spec:
  clusterIP: None
  ports:
  - name: etcd-server
    port: 2380
    protocol: TCP
    targetPort: 2380
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    component: riverflows-etcd-set-etcd-patroni-cluster
  sessionAffinity: None
  type: ClusterIP