apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "etcd-patroni-cluster"
spec:
  size: 3
  version: "3.1.8"
  pod:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    antiAffinity: true