apiVersion: v1
kind: Service
metadata:
  name: riverflows-pgwrite
  labels:
    component: patroni-patroni
spec:
  type: NodePort
  selector:
    component: patroni-patroni
    app: riverflows
    patroni-role: master
  ports:
  - port: 5432
