apiVersion: v1
kind: Service
metadata:
  name: riverflows-web
  labels:
    app: riverflows
    service: web
    tier: frontend
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: riverflows
    service: web
    tier: frontend