apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: riverflows
    service: web
    tier: frontend
  name: riverflows-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: riverflows
        service: web
        tier: frontend
    spec:
      containers:
      - command:
        - gunicorn
        - --log-level
        - info
        - -w
        - '2'
        - -b
        - :8000
        - wsgi:app
        envFrom:
        - secretRef:
            name: riverflows-secrets
        - configMapRef:
            name: riverflows-config
        image: gcr.io/alex-kerney/riverflows:0.1.6
        name: web
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 10m
