"""Added key to Gage for secret stuff

Revision ID: 18be97f93ad7
Revises: 175e7f040c99
Create Date: 2014-11-04 19:33:54.603870

"""

# revision identifiers, used by Alembic.
revision = '18be97f93ad7'
down_revision = '175e7f040c99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.add_column('gages', sa.Column('key', sa.String(), nullable=True))
    #op.drop_index('idx_gages_point', table_name='gages')
    #op.drop_index('idx_sections_path', table_name='sections')
    #op.drop_index('idx_sections_putin', table_name='sections')
    #op.drop_index('idx_sections_takeout', table_name='sections')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_sections_takeout', 'sections', ['takeout'], unique=False)
    #op.create_index('idx_sections_putin', 'sections', ['putin'], unique=False)
    #op.create_index('idx_sections_path', 'sections', ['path'], unique=False)
    #op.create_index('idx_gages_point', 'gages', ['point'], unique=False)
    op.drop_column('gages', 'key')
    #op.create_table('spatial_ref_sys',
    #sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    #sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    #)
    ### end Alembic commands ###
