"""Indexes on samples

Revision ID: 81dc076724ad
Revises: 3b5d923f174f
Create Date: 2017-06-03 21:00:47.333308

"""

# revision identifiers, used by Alembic.
revision = '81dc076724ad'
down_revision = '3b5d923f174f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('idx_gages_point', table_name='gages')
    op.create_index(op.f('ix_samples_datetime'), 'samples', ['datetime'], unique=False)
    op.create_index(op.f('ix_samples_sensor_id'), 'samples', ['sensor_id'], unique=False)
    # op.drop_index('idx_sections_path', table_name='sections')
    # op.drop_index('idx_sections_putin', table_name='sections')
    # op.drop_index('idx_sections_takeout', table_name='sections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_sections_takeout', 'sections', ['takeout'], unique=False)
    # op.create_index('idx_sections_putin', 'sections', ['putin'], unique=False)
    # op.create_index('idx_sections_path', 'sections', ['path'], unique=False)
    op.drop_index(op.f('ix_samples_sensor_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_datetime'), table_name='samples')
    # op.create_index('idx_gages_point', 'gages', ['point'], unique=False)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
