"""Indexes on gages, sensor

Revision ID: 88c36aab1133
Revises: c0ad64a90970
Create Date: 2017-06-03 21:26:48.182842

"""

# revision identifiers, used by Alembic.
revision = '88c36aab1133'
down_revision = 'c0ad64a90970'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.create_index(op.f('ix_gages_id'), 'gages', ['id'], unique=False)
    # op.drop_index('idx_gages_point', table_name='gages')
    # op.drop_index('idx_sections_path', table_name='sections')
    # op.drop_index('idx_sections_putin', table_name='sections')
    # op.drop_index('idx_sections_takeout', table_name='sections')
    op.create_index(op.f('ix_sensors_gage_id'), 'sensors', ['gage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensors_gage_id'), table_name='sensors')
    # op.create_index('idx_sections_takeout', 'sections', ['takeout'], unique=False)
    # op.create_index('idx_sections_putin', 'sections', ['putin'], unique=False)
    # op.create_index('idx_sections_path', 'sections', ['path'], unique=False)
    # op.create_index('idx_gages_point', 'gages', ['point'], unique=False)
    op.drop_index(op.f('ix_gages_id'), table_name='gages')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
