"""Indexes on gages

Revision ID: c0ad64a90970
Revises: 81dc076724ad
Create Date: 2017-06-03 21:04:28.986787

"""

# revision identifiers, used by Alembic.
revision = 'c0ad64a90970'
down_revision = '81dc076724ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.create_index(op.f('ix_gages_slug'), 'gages', ['slug'], unique=True)
    op.drop_constraint('gages_slug_key', 'gages', type_='unique')
    # op.drop_index('idx_gages_point', table_name='gages')
    # op.drop_index('idx_sections_path', table_name='sections')
    # op.drop_index('idx_sections_putin', table_name='sections')
    # op.drop_index('idx_sections_takeout', table_name='sections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_sections_takeout', 'sections', ['takeout'], unique=False)
    # op.create_index('idx_sections_putin', 'sections', ['putin'], unique=False)
    # op.create_index('idx_sections_path', 'sections', ['path'], unique=False)
    # op.create_index('idx_gages_point', 'gages', ['point'], unique=False)
    op.create_unique_constraint('gages_slug_key', 'gages', ['slug'])
    op.drop_index(op.f('ix_gages_slug'), table_name='gages')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
